using System.Collections.Generic;
using System.Linq;
using UnityEngine;
#if UNITY_EDITOR
using UnityEditor.SceneManagement;
#endif

namespace SplineMesh
{

    /// <summary>
    /// Deform a mesh and place it along a spline, given various parameters.
    /// 
    /// This class intend to cover the most common situations of mesh bending. It can be used as-is in your project,
    /// or can serve as a source of inspiration to write your own procedural generator.
    /// </summary>
    [ExecuteInEditMode]
    [SelectionBase]
    [DisallowMultipleComponent]
    public class SplineMeshTiling : MonoBehaviour
    {

        [SerializeField]
        public MeshPreset preset;

        [SerializeField]
        private Spline spline;

        [SerializeField]
        private float start;

        [SerializeField]
        private float end;

        private GameObject generated;

#if UNITY_EDITOR
        private bool toUpdate = false;
#endif

        private void OnEnable()
        {
            // tip : if you name all generated content in the same way, you can easily find all of it
            // at once in the scene view, with a single search.
            string generatedName = "generated by " + GetType().Name;
            var generatedTranform = transform.Find(generatedName);
            generated = generatedTranform != null ? generatedTranform.gameObject : UOUtility.Create(generatedName, gameObject);
            generated.hideFlags = HideFlags.DontSaveInEditor | HideFlags.DontSaveInBuild;

            if (!spline)
                spline = GetComponentInParent<Spline>();
#if UNITY_EDITOR
            spline.NodeListChanged += (s, e) => toUpdate = true;
#endif

            CreateMeshes();
        }

        public void CreateMeshes()
        {
#if UNITY_EDITOR
            // we don't update if we are in prefab mode
            if (PrefabStageUtility.GetCurrentPrefabStage() != null) return;
#endif
            var used = new List<GameObject>();

            if (preset.curveSpace)
            {
                int i = 0;
                foreach (var curve in spline.curves)
                {
                    var go = FindOrCreate("segment " + i++ + " mesh");
                    go.GetComponent<MeshBender>().SetInterval(curve);
                    go.GetComponent<MeshCollider>().enabled = preset.generateCollider;
                    used.Add(go);
                }
            }
            else
            {
                var go = FindOrCreate("segment 1 mesh");
                go.GetComponent<MeshBender>().SetInterval(spline, start, end);
                go.GetComponent<MeshCollider>().enabled = preset.generateCollider;
                used.Add(go);
            }

            // we destroy the unused objects. This is classic pooling to recycle game objects.
            foreach (var go in generated.transform
                         .Cast<Transform>()
                         .Select(child => child.gameObject).Except(used))
            {
                UOUtility.Destroy(go);
            }
        }

        private GameObject FindOrCreate(string name)
        {
            var childTransform = generated.transform.Find(name);
            GameObject res;
            if (childTransform == null)
            {
                res = UOUtility.Create(name,
                    generated,
                    typeof(MeshFilter),
                    typeof(MeshRenderer),
                    typeof(MeshBender),
                    typeof(MeshCollider));
                res.isStatic = !preset.updateInPlayMode;
            }
            else
            {
                res = childTransform.gameObject;
            }

            res.hideFlags = HideFlags.DontSaveInEditor | HideFlags.DontSaveInBuild;
            res.GetComponent<MeshRenderer>().material = preset.material;
            res.GetComponent<MeshCollider>().material = preset.physicMaterial;
            MeshBender mb = res.GetComponent<MeshBender>();
            mb.Source = SourceMesh.Build(preset.mesh)
                .Translate(preset.translation)
                .Rotate(Quaternion.Euler(preset.rotation))
                .Scale(preset.scale);
            mb.Mode = preset.mode;
            return res;
        }

#if UNITY_EDITOR
        private void OnValidate()
        {
            if (spline == null) return;
            toUpdate = true;
        }

        private void Update()
        {
            // we can prevent the generated content to be updated during playmode to preserve baked data saved in the scene
            if (!preset.updateInPlayMode && Application.isPlaying) return;

            if (toUpdate)
            {
                toUpdate = false;
                CreateMeshes();
            }
        }
#endif

    }

}
